"""empty message

Revision ID: 56688fc921e5
Revises: e6d10eaa8968
Create Date: 2024-03-03 21:09:37.534147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56688fc921e5'
down_revision = 'e6d10eaa8968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_organization'), 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
