"""empty message

Revision ID: aaa75344b9c7
Revises: 56688fc921e5
Create Date: 2024-03-05 14:20:34.684973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa75344b9c7'
down_revision = '56688fc921e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_organization', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_organization', 'course', ['course_id'], ['id'])

    # ### end Alembic commands ###
